### ISSUE TITLE
pytorch 2.0

### ISSUE THREAD

**Issue by fenaux** [JalaliLabUCLA/phycv#14]
I was impressed by your talk during NVIDIA GTC. Congrats.
Is it possible to use PhyCV with current version of PyTorch i.e. PyTorch 2.0

tanks for your help

**Comment by JalaliLabUCLA** [comment]
Thanks for your interest! Currently the code is only tested on PyTorch version 1.x. Feel free to test PyTorch 2.0 on your end and give us any feedback or suggestion on upgrading!

**Comment by fenaux** [comment]
I just deleted the lines concerning pytorch and torchvision in requirement.txt, then check results for the scripts on both CPU and GPU and everything seems correct

**Comment by JalaliLabUCLA** [comment]
Thanks for checking this out! However, we will upgrade to PyTorch 2.0 in the future after we do more test. Close this for now.
