### ISSUE TITLE
Determining the best VEViD parameters

### ISSUE THREAD

**Issue by zshn25** [JalaliLabUCLA/phycv#18]
Hi, I was wondering what is the best way to determine the most suitable parameters while using VEViD for low-light enhancement. I see that the following was used in the examples. Is it a good idea to always leave them the same?

`S = 0.2, T = 0.001, b = 0.16, G = 1.4`

**Comment by JalaliLabUCLA** [comment]
Hi, please check out the section 5.1 of the [paper](https://elight.springeropen.com/articles/10.1186/s43593-022-00034-y). We will also soon release the video on the robustness of the parameters.
