### ISSUE TITLE
Missing paraemeters

### ISSUE THREAD

**Issue by shersoni610** [JalaliLabUCLA/phycv#2]
Hello,,

The document says that there are two parameters for PST i.e. phase_strength and warp_strength. However,
in the pst.py I do not see these parameters. Am I missing something?

Regards

**Comment by JalaliLabUCLA** [comment]
Hi,
The `S` and `W` in the `init_kernel()` function correspond to `phase_strength` and `warp_strength`. Please check the comments of the functions in `pst.py`
