### ISSUE TITLE
Extracting lines at specific angles using PAGE 

### ISSUE THREAD

**Issue by glitchyordis** [JalaliLabUCLA/phycv#20]
Hello, may I know how can we extract lines that are at specific angles after getting output from page_gpu?

Example use-case is to determine the overall grain direction of an aluminum sheet.

**Comment by JalaliLabUCLA** [comment]
Hi,
PAGE extracts edges at different directions. The directions are specified by the `direction_bins`. For example if `direction_bins=10`, then it uniformly divides `pi` to 10 sections, and extract edges at these directions. See [this line](https://github.com/JalaliLabUCLA/phycv/blob/main/phycv/page_gpu.py#L101)

The edge information of these directions are saved in the `page_feature`. See [this line](https://github.com/JalaliLabUCLA/phycv/blob/main/phycv/page_gpu.py#L141). You can access `page_feature` to get the edge information at different directions.
